/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.project;

public class App {
    public int Age;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    // TODO : Add Static Method 
}
